### ISSUE TITLE
4512703 Switch release event not working

### ISSUE THREAD

**Issue by ivan-skjavik** [NamronAS/Namron_Homey#100]
Hi,

On the switch with 4 groups (4512703) the release event is not working it seems.
It's impossible to make a "hold to dim" function because it will just dim to max endpoint of the light is reached.

Currently this is the flow:
![image](https://github.com/NamronAS/Namron_Homey/assets/87182260/214ef150-dcf4-4a63-9392-3bb2843dfee0)

The switch with 2 groups is working perfectly.

Is this an easy fix?

**Comment by ivan-skjavik** [comment]
I tried debuging the "released" event with a timeline notification, but it does not register.

**Comment by ivan-skjavik** [comment]
Thanks for the reply.

It believe that i can upgrade it with a deconz module. I will give it at try.

Where can i find the opdated firmware file?

**Comment by prj84** [comment]
We have it in test as we speak, please contact me on pal.hefre@namron.com Then I will send it to you for test :-)

**Comment by prj84** [comment]
Issue is resolved - New firmware and recall
