### ISSUE TITLE
Zigbee Panel ovn homey pro

### ISSUE THREAD

**Issue by RohnnyS** [NamronAS/Namron_Homey#105]
Its not possible to adjusy offset on the temperature. Nothing happens regardless what number to put in.

**Comment by prj84** [comment]
@maginawin - Could you have a look at this? :-) Zigbee panel heater

**Comment by RohnnyS** [comment]
Yes, i Can. This is what i installed is as 540139 Zigbee Panel...When i look at setting it looks like a hester butThis is what is says. Look at attchmentMvh Rohnny Stormo Sendt fra min telefon
-------- Opprinnelig melding --------Fra: Pål Hefre ***@***.***> Dato: 22.08.2023  12:26  (GMT+01:00) Til: NamronAS/Namron_Homey ***@***.***> Ko: RohnnyS ***@***.***>, Author ***@***.***> Emne: Re: [NamronAS/Namron_Homey] Zigbee Panel ovn homey pro (Issue #105) 
@maginawin - Could you have a look at this? :-) Zigbee panel heater

**Comment by prj84** [comment]
Hi!
Latest app update should have fixed the issue
Please reopen if still a issue

https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by RohnnyS** [comment]
Hi. This was not fixing the problem. I have 25 degree on external degree measure. My ovn stand on 17.  and the ovn temperatur says 20.20 on 0 calibrationAnd 20.10 on 40 so that is not working. The ovn is product id 5401398Firmware version6.9.1.0_r4Mvh Rohnny Stormo Sendt fra min telefon
-------- Opprinnelig melding --------Fra: Pål Hefre ***@***.***> Dato: 18.12.2023  09:34  (GMT+01:00) Til: NamronAS/Namron_Homey ***@***.***> Ko: RohnnyS ***@***.***>, Author ***@***.***> Emne: Re: [NamronAS/Namron_Homey] Zigbee Panel ovn homey pro (Issue #105) 
Hi!
Latest app update should have fixed the issue
Please reopen if still a issue
https://homey.app/no-no/app/net.filllip-namron/Namron/test/
