### ISSUE TITLE
4512748 Missing tilt capabilities

### ISSUE THREAD

**Issue by JOR200** [NamronAS/Namron_Homey#106]
I have several Z-Wave blinds controllers that works fine. But, I really miss the ability to tilt the blinds in small steps. In my case it takes about 3% of the total blind posision to tilt all the way. (this may vary based on the hight of the windows and so on.)
If I raise the blinds position by 1%, my blinds tilt too less. Raising posision by 2% is too much.
Is it possible to add a slider for tilting the blinds in smaller steps than 1% of the total position?

**Comment by prj84** [comment]
@maginawin - Possible to add, or is it a Homey restriction?

**Comment by JOR200** [comment]
It looks like the z-wave device supports tilting.
I think Homey at least will support setting a value for parameter 13 on the device based on a slider position.

**Comment by JOR200** [comment]
Here is the documentation for the device:[https://www.elektroimportoren.no/docs/lib/4512748-Brukerveiledning-5.pdf](url).
Can I use the Rawconfig option under Advanced settings for the device to set configuration parameter 13? If so, what would be the syntax for setting this parameter to 15 (1.5 sec)? 
![image](https://github.com/NamronAS/Namron_Homey/assets/59866495/2151f103-5d99-4920-8fb4-f3cfadb35684)

**Comment by JOR200** [comment]
I found the syntax and was able to change parameter 13 to 1,5 sec. with this value: 13,1,15
Result: When moving blinds up or down stops, the blinds will automatically tilt in the opposite direction for 1,5 secs.

@prj84 
It would be nice to have this tilt value as a slider for the device. It would also be nice to read or set tilt value by flowcards.

**Comment by prj84** [comment]
Hi!
We have asked the developer for a rewrite on this device. It has been added to the ToDo list

**Comment by prj84** [comment]
Added in 2.2.90 that will be released soon
