### ISSUE TITLE
Set heating mode in flows (Z-wave thermostat)

### ISSUE THREAD

**Issue by Ahaano** [NamronAS/Namron_Homey#108]
Hi,

In Homey, I'm able to set the heat mode when I'm controlling the thermostat directly, like in the image below:
![Namron](https://github.com/NamronAS/Namron_Homey/assets/25844740/ab5d12cc-4927-4b71-865c-54b1c5d3c7be)

But when I create a flow, I only have the options to turn the thermostat ON/OFF or set a specific temperature.
I would love to be able to say that "IF X happens, set the thermostat mode to Dry", 

Would that be possible?

-Anders

**Comment by prj84** [comment]
Added in 2.2.90 that will be released soon
