### ISSUE TITLE
4-channel zigbee remote, scene buttons not working

### ISSUE THREAD

**Issue by Eivinde89** [NamronAS/Namron_Homey#109]
Hello

On my 4-channel zigbee remote, the scene buttons does not respond.
I have tried activating several items in an advanced flow, where the other buttons work well as intendend. I have shuffled the flow cards around, but the scene buttons will not activate anything.

I am on a Homey Pro 2023 with the lastes software.

Thanks in advance

Best regards

**Comment by prj84** [comment]
Hi! Is this still a issue after lates app update?
https://homey.app/no-no/app/net.filllip-namron/Namron/test/
