### ISSUE TITLE
4512706 - Dont work with Homey in any way

### ISSUE THREAD

**Issue by ArcAngle** [NamronAS/Namron_Homey#111]
After a lot of tries, I finally managed to add the remote to my homey, but no matter what function I try to use, there is no response on the triggers. Nothing is received from the remote. I have tried to log all traffic, and there is nothing. this is one in a series of many Namron products I have bought that don't work as intended or at all.

I have also tried to add it to a ZigBee network, and it still doesn't work at all. It's just a nice mantelpiece as everything else Namrom.

**Comment by ArcAngle** [comment]
The question is, are you going to fix any problems with Namron products Z-wave or ZigBee, connected to Homey? or do you intend to keep saying that it is compatible with Homey just for show?

**Comment by ArcAngle** [comment]
So, I guess this means you are not going to do anything about it? Nice to know that you take customers seriously.

**Comment by prj84** [comment]
The problem has been reported to the developer. Please contact our support center if you have any more problems with your Namron device.
