### ISSUE TITLE
Secure vs unsecure - question

### ISSUE THREAD

**Issue by tholden92** [NamronAS/Namron_Homey#114]
Hi,

just wondering if there is any reason why the dimmer switches and relays are added in secure mode, when the physical dimmers are not?

As far as I understand it, there is only upsides in disabling secure mode.

**Comment by prj84** [comment]
Hi! From version 7 of Homey all devices are forced to use their highest possible security mode. We have been in contact with Athom for a way to force devices to be unsecure, but at this point there is only unoffical ways of doing this. We really understand the frustration and have this as one of our highest prioreties.

**Comment by prj84** [comment]
We have tried to tweak the drivers in latest app update. Can ypu please check with test version of the app if it now includes unsecure. :-)

**Comment by tholden92** [comment]
I can confirm that the devices are still added secure, unless you use the unofficial unsecure app.

**Comment by tholden92** [comment]
Ah, no sorry. I think I was wrong. Tested again, and now it is unsecure. 
<img width="1418" alt="image" src="https://github.com/NamronAS/Namron_Homey/assets/56877833/2940ef36-43d3-4d9f-8262-dd92a449c1a9">
