### ISSUE TITLE
Namron 4512725

### ISSUE THREAD

**Issue by Cenit12** [NamronAS/Namron_Homey#116]
This thermostat is not working as thermostat. I have three installed on my Homey 19 and none of them working. I have tried to install them as thermostats and as switches but none of the options is working as thermostat.
I can adjust the temperature in the app but they don’t activate to switch on when temperature is set above ambient temperature. The app change color from blue to orange but no power comes to the connected heating element.

**Comment by prj84** [comment]
These thermostat plugs are configured as smart plugs as standard. It is therefore important that you select thermostat when selecting Plug Mode. When this option is set to Thermostat it will turn off based on the selected temperature.
