### ISSUE TITLE
Change thermostat sensor type from flow

### ISSUE THREAD

**Issue by cbakk1** [NamronAS/Namron_Homey#117]
Hi, I have Namron Z-Wave thermostats (4512757) in two rooms with water systems at my cabin. Normally, I would like to use the floor sensor, but due to the slowness of temperature changes in the floor I would like to set sensor mode A (room temp) when I’m not at the cabin in the winter, to prevent water in the rooms from freezing. Is this possible to implement?

**Comment by prj84** [comment]
Hi! I will ask developer if it is possible

**Comment by prj84** [comment]
We have added this to a nice to have list, but for now not planned,
