### ISSUE TITLE
Namron Zigbee Smart plug 4512749-N stuck in Thermostat mode

### ISSUE THREAD

**Issue by ce7641** [NamronAS/Namron_Homey#118]
I am configuring  the smart plug Namron Zigbee Smart plug 4512749-N  on a Homey Pro 19. I try to switch the mode the smart-plug is operating in from "Thermostat Mode" to "Plug Mode/Switch Mode". I want just ON/OFF capabilities without touching temperature settings. It is used for lights and I do not want to use temperature settings to trigger on/off. I just want ON/OFF plan and simple.  But no matter what I try the configuration just reverts to Thermostat mode? I want the device to be i Plug Mode all the time. What is wrong here? Why is this simple operation failing? Any ideas?

**Comment by prj84** [comment]
Hi!
I have tested this now and can not find any problem.
Please see attached video

https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2F5EtNPwuK-M4%3Fsi%3D35pTVDJrF-9GaIVy&data=05%7C01%7Cpal.hefre%40namron.com%7Cca72e762d9c140cb689a08dbd6c2b25b%7C6b5be421e9824beeabe153d6c7dddf9c%7C0%7C0%7C638339903924758733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4t3cetr9FVCxbYnAYrEHJYfaWymSeWhsQa7qjNInY98%3D&reserved=0
