### ISSUE TITLE
Heater 5401397 reset

### ISSUE THREAD

**Issue by Runeamalmo43** [NamronAS/Namron_Homey#121]
Almost instantly after including in homey, the heater automaticly factory reset.

Not product defect, have tried different ones. 
Have a simular unit, only 400w edition. It dpen kot have simular problems.

**Comment by prj84** [comment]
Hi! Do I understand that this happens with different panel heaters or just 1? Can you please chech batch number on the panel heater? it is a sticker with month/year (ex. 04/22)
