### ISSUE TITLE
Homey (app) crashes when trying to add Namron device

### ISSUE THREAD

**Issue by kjoms** [NamronAS/Namron_Homey#123]
This is an issue after migrating from Homey 2019 to Homey 2023.
Any try to add a new Namron device results in a crach some seconds after clicking "connect" after selecting device.
I was able to add my Namron heaters as generic Zigbee devices but not my other devices.

**Comment by prj84** [comment]
Hi! What kind of device craches the app? :-) Please try to remove and readd the app if possible
