### ISSUE TITLE
Dimmer 4512750

### ISSUE THREAD

**Issue by FrodeHernes** [NamronAS/Namron_Homey#124]
Hi,

There are a couple of problems with the new, one-pool Namron dimmer:
 - It is not visible as a choiche when trying to add a new device using the Web Homey interface, - only when using the iOs App.
 - The device was not properly recognized and gave the messae "it seems you have not the proper app installed, so installed as an Unknown Zigbee Device.
 - 
![IMG_0587](https://github.com/NamronAS/Namron_Homey/assets/129166898/a1246a5f-c4f6-4e61-a66c-8a107496cd89)

Frode

**Comment by FrodeHernes** [comment]
App version 2.2.69

**Comment by FrodeHernes** [comment]
And Homey Pro 2019

**Comment by prj84** [comment]
Hi! Can you please send a screenshot of the advanced page of the device :-) Just to chech product number etc.

**Comment by FrodeHernes** [comment]
This one?

[A screenshot of a computer  Description automatically generated]



From: Pål Hefre ***@***.***>
Date: Tuesday, 7 November 2023 at 13:23
To: NamronAS/Namron_Homey ***@***.***>
Cc: Frode Hernes ***@***.***>, Author ***@***.***>
Subject: Re: [NamronAS/Namron_Homey] Dimmer 4512750 (Issue #124)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi! Can you please send a screenshot of the advanced page of the device :-) Just to chech product number etc.

**Comment by prj84** [comment]
Hi! Can't really see any screenshot attached to this message :-) Can you try to resend?

**Comment by prj84** [comment]
Still can not see any attached picture in the thread on Github. I need a screenshot from the advanced setting screen to see Manufactor ID and Product ID. This is used to identify the product in Homey.

**Comment by FrodeHernes** [comment]
Aha, - I did not see that your message was from Github and just answered with a normal mail message.

This hopefully works:

![image](https://github.com/NamronAS/Namron_Homey/assets/129166898/b431a717-2bd3-4513-a2be-e4ddef4d3be2)

**Comment by prj84** [comment]
Ahh!
Thanks! I have added correct information, so should be updated in app in next release or in testapp in just a few moments :-)
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by FrodeHernes** [comment]
Ok,

Thanks!
