### ISSUE TITLE
4512757 Zwave Thermostat - Device unavailable

### ISSUE THREAD

**Issue by MSrDE** [NamronAS/Namron_Homey#130]
with the latest update 2.2.75 devices are viable in the development mode, but not in the homey app and it is not possible to remove and add them back in

![IMG_2869](https://github.com/NamronAS/Namron_Homey/assets/115079521/2098137e-5c51-4608-9d65-95b6dd0dd67e)
![IMG_2868](https://github.com/NamronAS/Namron_Homey/assets/115079521/66d8c2bb-b510-44cc-bc10-f08d2a6ae146)
![IMG_2867](https://github.com/NamronAS/Namron_Homey/assets/115079521/6ee282ac-3c81-43f6-9c8c-5100fac77232)

**Comment by bgronli** [comment]
Same issue for me :-(

**Comment by FrankLyder** [comment]
Same for my installation. 
Has created a diganostic report "b4fe6031-7adf-496b-933e-198c484751fd"

**Comment by kberge72** [comment]
Guess this is a issue for many. Same for me

**Comment by prj84** [comment]
Manufactorer are working on a fix

**Comment by prj84** [comment]
https://homey.app/no-no/app/net.filllip-namron/Namron/test/
Please use the test version of the app to solve the issue for now
