### ISSUE TITLE
Set thermostat scheduling via Homey

### ISSUE THREAD

**Issue by aaronaes** [NamronAS/Namron_Homey#131]
Is there a way to set auto day scheduling via the Homey app? Or does is it have to be done via the thermostat itself? 

If it’s not possible as of today, it would be an amazing feature to add down the road.

I’m brand new to Homey, so maybe I missed it in the app.

**Comment by prj84** [comment]
At this point this is not planned for the app. Use flows to adjust temp and set scheduling
