### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by olahelgedagsrud** [NamronAS/Namron_Homey#134]
Homey integration is crashing and contact with devices stop![image](https://github.com/NamronAS/Namron_Homey/assets/53524822/3d376e6b-115e-410a-b8da-631061965b45)

**Comment by maemeloy** [comment]
Samme problem

**Comment by Kaare69** [comment]
I have same problem. Can Namron please roll back to previous working release imidiatly please.

**Comment by prj84** [comment]
https://homey.app/no-no/app/net.filllip-namron/Namron/test/
Please use the test version of the app to solve this for now
