### ISSUE TITLE
Power meetering for the 451276x - Zigbee Smart Plug 16A

### ISSUE THREAD

**Issue by Daggulb** [NamronAS/Namron_Homey#140]
I experience with several of these plugs that i get sudden peaks in the power meetering report, when the switch is powered off. Typically a sudden peak of close to 25KW (which of course is far above the max 3.3KW range for this plug., will show once or more in the past hour report.

Has other experienced the same, and are there ways of handling this (apart from replacing the plug, but as it occurs on several, I guess it's a "thing" with these plugs in general)

![Screenshot_20231123-065948_Homey](https://github.com/NamronAS/Namron_Homey/assets/131396949/3ec9abaa-b921-4274-beb8-9701896c1389)

**Comment by prj84** [comment]
Manufactorer is on the problem. It will take some time since this seems to be a random error.

**Comment by masollid** [comment]
Same for both of mine smart plugs

**Comment by henrist** [comment]
I had the same problem back in January and contacted Namron / Elektroimportøren. They sent me an OTA firmware update (see attached) that solved the problem for me. I don't know if there is anything newer since January. I tried to ask them if there's a place for these files, but they didn't respond to that request.

[Namron_AS_4512766_V1.18_20240119_1600.ota.zip](https://github.com/NamronAS/Namron_Homey/files/15282522/Namron_AS_4512766_V1.18_20240119_1600.ota.zip)

**Comment by henrist** [comment]
@masollid What system do you use?

I use Home Assistant with zigbee2mqtt, for which https://www.zigbee2mqtt.io/guide/usage/ota_updates.html describes the process. If you also use zigbee2mqtt this is what I did:

Edited the `config/zigbee2mqtt/configuration.yaml` file and added:

```yaml
ota:
  zigbee_ota_override_index_location: my_ota_index.json
```

And `my_ota_index.json` in the same directory contain:

```json
[
    {
        "fileVersion": 9,
        "fileSize": 283302,
        "manufacturerCode": 4098,
        "imageType": 1002,
        "sha512": "85df643d0598655b334c51e243be3e6986fe88f0d406d7d8c5ae65c53d22c9e387038949ac6176dbaa0a451fe2e8b1b45df63f27d95c41d4ef801f9fa3b3d323",
        "url": "Namron_AS_4512766_V1.18_20240119_1600.ota",
        "path": "Namron_AS_4512766_V1.18_20240119_1600.ota"
    }
]
```

The file in the Zip I provided was extracted to the same directory. After all this check the device in zigbee2mqtt for updates. I did this a few months ago, so hope I didn't forget about something.

**Comment by masollid** [comment]
I only have the homey pro 2023

**Comment by henrist** [comment]
I don't know much about Homey, but searching a bit it seems Homey cannot do this. You probably need to get something else you can pair your device to and do the update from. I recommend searching a bit more around this to get a better overview.
