### ISSUE TITLE
Namron zigbee LED dimmer 2.0/ 4512750 

### ISSUE THREAD

**Issue by kalimax89** [NamronAS/Namron_Homey#148]
Hi! 

Im struggeling to pair this Namron zigbee LED dimmer 2.0. 
Both on the app and  manual says that the status indicator will turn into blue when it has been paired. 
it doesn’t seem any status indicator on this device? 
any ideas? 
appreciate for the help. 

![IMG_2226](https://github.com/NamronAS/Namron_Homey/assets/92652961/60b8a07b-e587-4284-b630-2c89f0adef41)
![IMG_2228](https://github.com/NamronAS/Namron_Homey/assets/92652961/fdc69a3d-5f3e-415b-9a1f-088f2c250fca)
![IMG_2229](https://github.com/NamronAS/Namron_Homey/assets/92652961/e9160ed6-6b7d-4149-8708-c1376fcf6c14)
![IMG_2227](https://github.com/NamronAS/Namron_Homey/assets/92652961/99ea78f5-8e5b-4018-9957-aec45ca92010)
![IMG_2230](https://github.com/NamronAS/Namron_Homey/assets/92652961/5ff2070a-ee03-4937-9929-4be918576cdb)

**Comment by prj84** [comment]
Please contact Elektroimportøren/Namron support center
