### ISSUE TITLE
Test-version of app (v2.2.84) - Error message with thermostat 4512758

### ISSUE THREAD

**Issue by skog7** [NamronAS/Namron_Homey#151]
Using the test-app due to lack of support for my thermostat in the regular app. Communication worked fine up until this afternoon so it looks like the error was introduced in v2.2.84 released 07.12.2023. 

Currently I get an error message whenever i open the device in Homey and no flows are working. Error message is: 

Error: Expected attribute names array, as of zigbee-clusters@2.0.0 call readAttributes(['myAttr']

Please fix? :)

**Comment by lQnning** [comment]
I have the same issue on Homey, both at the cabin and at home. In total, I have 4 thermostats.
