### ISSUE TITLE
Panel heaters stop reporting energy and power statistics

### ISSUE THREAD

**Issue by n808** [NamronAS/Namron_Homey#153]
Both my Namron panel/wall heaters have stopped reporting energy and power statistics, but can still be remote controlled via Homey. The target temperature and current temperatures are reported correctly.

Since it affects both panel heaters exactly the same (no reports for 2 days now), this appears to be a bug in the app. This is a significant problem, as I am keeping track of energy costs using Power By The Hour summarizers. 

App version 2.2.76 
Manufacturer ID: NAMRON AS
Product ID: 5401393
Firmware: 6.9.1.0_r4
Homey Pro 2023

Diagnostics report sent: f3ceed03-c4e1-4e41-9a8a-a8f84c9ff1d0

I just updated to the 'test' version, 2.2.85.  Then I increased target temperature to turn the heater on. Power is reported again (~600W) power, then a huge negative number blinked, before it went back to approximately 600W again. Cumulative energy is now just '-', it was 92kWh two days ago. This is the most important statistic I need to keep track of cost and now PBTH thinks the heater used -92kWh the last hour. Both heaters appear to have the same problem with 2.2.85: cumulative energy reported as zero (or not reported, unsure). 

No issues with energy statistics for any of my other brand of devices.

**Comment by n808** [comment]
Thanks for following up.

With 2.2.76, one can get both numbers (instant and cumulative) to work temporarily, by adding the heater as a new device (the "repair" function does not help). But then after a reboot of Homey, both numbers yet again stop reporting in.

**Comment by prj84** [comment]
I close this since we have another tread

**Comment by klillevo** [comment]
It seems energy and power reporting got back on track after restarting the app. I did not have to delete the units and re-add the units again as before.
