### ISSUE TITLE
“Could not get device by id” namron v2.2.76 and 451275x thermostat

### ISSUE THREAD

**Issue by kjetilhorneland** [NamronAS/Namron_Homey#161]
Issue: when adding the namron app to homey and setting up my 4512758 thermostat (as 451275x) the device registers but no actions can be performed. It only returns the error message “could not get device by id”. Connecting without namron works, so this seems like a bug?

![IMG_3610](https://github.com/NamronAS/Namron_Homey/assets/154628472/6bdb6085-24f5-4e28-881c-3000a2de0ebc)

**Comment by prj84** [comment]
Please use the namron test version.
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by kjetilhorneland** [comment]
Thank you, that solved the issue! Much appreciated!
