### ISSUE TITLE
4512758 set as smart meter

### ISSUE THREAD

**Issue by lordradon** [NamronAS/Namron_Homey#163]
The 4512758 thermostats are set as smart meters in energy in homey 2019. See attached picture. 

Using test version 2.2.88

Had to remove the thermostats from overall energy consumption, to get an accurate picture of energy being used. Hope you can fix this issue. 

![IMG_20231226_025817](https://github.com/NamronAS/Namron_Homey/assets/29264129/c206bce2-0b95-4cc0-a3ae-2cc8fdafb671)

**Comment by prj84** [comment]
Forwarded to developer, thanks for feedback

**Comment by prj84** [comment]
Fixed in 2.2.90 that will be released soon
