### ISSUE TITLE
Clock setting on touch thermostat

### ISSUE THREAD

**Issue by dan-sone** [NamronAS/Namron_Homey#179]
Is it possible to set the clock on 4512737/38 - Zigbee Thermostat Touch?
Either automatic or manually.

Thanks,
Dan

**Comment by prj84** [comment]
Hi! You have to set it manually in the settings of the thermostat.

![image](https://github.com/NamronAS/Namron_Homey/assets/35060010/37127ef9-26b4-4307-9e07-df3d9f8abf25)
