### ISSUE TITLE
4512758/9 timeout issue

### ISSUE THREAD

**Issue by kjetilhorneland** [NamronAS/Namron_Homey#186]
Unable to control my thermostats. When trying to adjust temperature from homey I get a timeout message and the thermostats are dimmed. See attached. Namron v 2.2.93
![IMG_3956](https://github.com/NamronAS/Namron_Homey/assets/154628472/19b8b39a-68f9-42a6-9c8d-f35fe1c650fa)
 

![IMG_3953](https://github.com/NamronAS/Namron_Homey/assets/154628472/c024565f-90e7-4397-b532-d5a71d890cb5)
![IMG_3954](https://github.com/NamronAS/Namron_Homey/assets/154628472/87480a94-2b54-46b2-b8c6-08b4b2efffa0)
![IMG_3955](https://github.com/NamronAS/Namron_Homey/assets/154628472/160422f0-4aee-4027-8e0c-0bdce3eab639)

**Comment by prj84** [comment]
Hi! Homey Pro or Homey Bridge?

**Comment by kjetilhorneland** [comment]
Homey bridge. Turning off and on the power on the homey seemed to resolve it for now, but I guess it was still a bug.
