### ISSUE TITLE
All Namron devices disconnecting daily / App crash?

### ISSUE THREAD

**Issue by thor-erik** [NamronAS/Namron_Homey#187]
Every morning for the past 3-4 days the Namron app seems to have lost connection with all of my devices. Restarting the app seems to temporarily solve the issue. I restarted the app this morning, but had to do it again this evening.

Here are my devices.
![Screenshot_20240212-180113](https://github.com/NamronAS/Namron_Homey/assets/127342479/f81d596f-5396-409f-a5c0-556e11f6dacc)

**Comment by prj84** [comment]
Hi! Next time this happens, please make a diagnostic report in the app preferances as soon as possible before restarting the app. Please provide write "app crash daily" as referance.

**Comment by thor-erik** [comment]
It happened this morning as well. Sent inn i report just now with the
reference.

31c359e9-e5b7-4b47-8bb6-40d6cf94f2d8

ons. 14. feb. 2024, 13:03 skrev Pål Hefre ***@***.***>:

**Comment by prj84** [comment]
that came back empty, can you please come back with a time stamp for when it happens next time. Then I will look through the automatic logs

**Comment by thor-erik** [comment]
Happened again just now. Timestamp exactly 22:30:00. I set up a flow that
sends a notification when all devices are not responding, but this flow
only updates every 30 min. So the actual timestamp may also be 22:00:00. I
would check both timeslots.

Regardless I sent in another diagnostic, code here:
5045dfe2-1d65-48bd-9ef9-0d6f24c12f98

Thanks for your help and responsiveness 🙌

ons. 14. feb. 2024, 13:14 skrev Pål Hefre ***@***.***>:

**Comment by prj84** [comment]
Also came back empty.... hmmm... Seems that all log history is wiped when app crashes. Could you please send me the device list of Namron devices

**Comment by thor-erik** [comment]
8x 1402755
1x 89664
4x 4512638

Med vennlig hilsen / Best regards

Thor Erik Norbom

tor. 15. feb. 2024, 15:05 skrev Pål Hefre ***@***.***>:

**Comment by stiglinga** [comment]
Hi,
I am struggeling with the same issue (last couple of days). I shall also try to make a report.
- Stig Linga

**Comment by stiglinga** [comment]
It happened again this evening, i have the diagnostic code: a4577495-0a4a-4bb5-acc5-4ac0c37fe430

Br Stig Linga

**Comment by thor-erik** [comment]
It's becoming worse. It seems that I lose connection with all my devices now, but Homey does not recognize that the app has crashed. Restarting the app does not seem to resolve the issue either. Any progress on finding out the issue? Happy to help here.

**Comment by prj84** [comment]
We have opened a case agains Athom to try to resolve this issue. We can't find anything in logs other than TimeOut on all zigbee devices.

**Comment by lordradon** [comment]
5d849c7d-69e9-4754-8ea1-0af64e74ed8a

Happens every day here to. Latest update.

**Comment by stiglinga** [comment]
Still the same issue, often more than once a day, requires restart of homey for regaining connection. No better after the latest updates, maybe even worse. WAF is rapidly decreasing.

**Comment by lordradon** [comment]
![Screenshot_2024-03-13-12-14-45-69_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/NamronAS/Namron_Homey/assets/29264129/6b94344d-6107-4a62-9844-764925c8cf96)


So bad, I can't even press restart app 👀

**Comment by cbakk1** [comment]
@lordradon Disable / enable the app will have the same effect as restart. I too hav to do this periodically now, HP2019 10.0.7

**Comment by stiglinga** [comment]
I have a Connecte floor heating thermostat that now seem to act the same way. This makes me wonder if it could be a Homey issue in general, and not just the Namron app.
