### ISSUE TITLE
Zigbee Namron device dimmer 2 400 w leaves the network involuntary 

### ISSUE THREAD

**Issue by JonBla17** [NamronAS/Namron_Homey#199]
Zigbee Namron device dimmer 2 400 w leaves the network involuntary Type 4612760. A error report is generated below.

Different type of device in same network regularly stops responding and works after power sycle by switching the fuse.

Is it a fix for this issue?
![IMG_0510](https://github.com/NamronAS/Namron_Homey/assets/165931696/ffe3b4f4-e424-4776-918d-322fb3615a05)

Please advice.

Homey Pro 2016-2019 10.0.9 app 8.0.2.1450
Namron v2.2.95

Error report
2e673d9e-72c6-43e2-ad2a-07a0002b3c5f

**Comment by prj84** [comment]
This issue should be resovled in a earlier update. Please reopen if still a issue.
