### ISSUE TITLE
All Namron Panel Oven Zigbee and all Namron Thermostat Z-wave app displays frozen and empty in my Homey Bridge with Premium

### ISSUE THREAD

**Issue by EdgarJellum** [NamronAS/Namron_Homey#213]
I set up my Home Bridge Premium at 2024.05.8 with:

- 1 pcs Fibaro Motion Sensor
- 1 pcs Namron Relay 16 A Z-wave
- 1 pcs Namron Thermostat Switch Z-wave
- 2 pcs Namron Thermostat Z-wave
- 9 pcs Namron Panel Oven Zigbee
Everything has been working fine until I logged in yesterday 2024.05.29. Before that I checked the system approx 2024.05.25 and at that time everything was OK.

When I logged in yesterday 2024.05.29 I have problems with all Namron Thermostat Z-wave units and all Namron Panel Oven Zigbee units. **The other components in the list above works fine**.

The problems are the same for all the 2 + 9 buggy units:

- Opening the detail display in my iPhone Homey app gives me an empty display. The settings button in the upper right corner gives me an ok settings display
- Opening the detail display for the 2+9 buggy units on the WEB-app gives my an empty display except for the top row with name, settings button ++ and the bottom row with buttons for the different displays. BUT the button for the Event-list is missing
- Clicking the settings button in the detail display in the WEB-up brings up the settings display which seems OK.

Since the 3 first components in list of component works normal and the Home Bridge details display also say that everything is fine it seems that my Home Bridge is working.

To me it seems to be a problem with the Namron app for the two object types thermostat and panel oven or that something has happened with part of my configuration.
Nobody has been logged into the system between 2024.05.25 (system ok) and 2024.05.29 (buggy system).

My Homey Bridge is installed in a vacation house and I am currently 4 hour drive away from that site. I have not been at the place since 2025.05.11 the system was installed
Today I created a diagnostic report with ID 94510D22.

Please advice on how I can get the system running again. Hopefully without going to the side.

Regards
Edgar

**Comment by EdgarJellum** [comment]
Just to give a more precise info of the type of components where I have problems: 
4512744 Namron Z-Wave Touch Termostat
540139* Namron Panel Oven

From https://homey.app/en-us/app/net.filllip-namron/Namron/ it seems that the Namron app was updated 3 days ago to version 2.2.99. I presume that my Homey is updated automatically.

Can this update be the cause of my problems?

Edgar

**Comment by larstun** [comment]
> Just to give a more precise info of the type of components where I have problems: 
> 
> 4512744 Namron Z-Wave Touch Termostat
> 
> 540139* Namron Panel Oven
> 
> 
> 
> From https://homey.app/en-us/app/net.filllip-namron/Namron/ it seems that the Namron app was updated 3 days ago to version 2.2.99. I presume that my Homey is updated automatically.
> 
> 
> 
> Can this update be the cause of my problems?
> 
> 
> 
> Edgar

I have the same problem with 6 of my Namron Panel Oven. Tried to factory reset one of the oven and reinstall that oven to the Homey app but the configuration stops and gives me this error message: ![image](https://github.com/NamronAS/Namron_Homey/assets/143407861/2f31681c-1095-403c-b52a-e69d03050582)

**Comment by EdgarJellum** [comment]
The problem with no response from all 540139* Namron Panel Oven units and all 4512744 Namron Z-Wave Touch Termostat units was detected 2024.05.29.
When I logged into Homey 2024.06.07 everything was working fine again. I had not been physically present at the location where the system is installed but I had logged in many time between the two dates and every time there were no response from the listed units.
Approx one week before the problem was detected 2024.05.29 all  540139* Namron Panel Oven units were set to mode Off and all 4512744 Namron Z-Wave Touch Termostat units were set to mode Away. During the period with no connection there were no notifications from Homey indicating problems. When the problem was gone 2024.06.07 I checked the temperature logs on all the panel ovens and both thermostats for the problem period and there were temperature logs available for all units. This means that the communication between the units and Homey had been working.
We cannot find a reasonable explanation why the connection were OK again There were people at the site 2024.06.05 and they powered off/on all panel ovens except one to make the ovens start heating and the setpoint was increased locally on the two thermostats. I am not 100% sure, but I think I was logged in to Homey after the local actions had happened and that the problem still existed. But as I have written above 2024.06.07 everything was fine again.

We need to find out why this problem occurred so this can be prevented from happening again. Homey Bridge was selected to make us able to control the heating remotely and we need a reliable system. I have no earlier experience with the Zigbee 540139* Namron Panel Oven but I have been using the Z-wave 4512744 Namron Z-Wave Touch Termostat together with Fibaro Home Center 3 Lite for more than a year in another house without any problems.

Please advise on how to avoid the described problem

@larstun , have you fixed the problem with your Namron panel oven?

**Comment by larstun** [comment]
@EdgarJellum i have experienced similar issues as you during the same time-period, so it cant be something local. I tried to factory reset one of the oven but it just failed during this period, and one week later the other ovens appeared again in the app.

**Comment by prj84** [comment]
We have been informed that there has been an error on one of the cloud servers generating this error in a time period. It is now fixed and similar problems should not accure. I'm closing this for now, but please report back if you get same problem later.
