### ISSUE TITLE
Namron Z-Wave Relé 16A (4512746) and device classification

### ISSUE THREAD

**Issue by MNHPetersen** [NamronAS/Namron_Homey#22]
Since this relé can be used for different purposes I wish it would be possible to change the device classification in advanced settings. Now it's classified as light and my usage is other than light. I don't wish to turn this off when I turn off the light in zones with flows.

**Comment by MNHPetersen** [comment]
After changing contact lenses I saw it in the settings... 😂

**Comment by MNHPetersen** [comment]
And I'm back. Can you please add "Heater" as a device classification?

**Comment by prj84** [comment]
Comes in v2.2.57 update of app. Waiting for certification, but is in test as we speak :-)
