### ISSUE TITLE
Powermeter

### ISSUE THREAD

**Issue by Finn-Cato** [NamronAS/Namron_Homey#225]
I have a namron puck dimmer2 400w (zigbee), it often shows errors on power consumption, when it should show 50w it shows 500w or it should show 100w then it shows 1kwh, is this something that can be fixed?

**Comment by prj84** [comment]
Hi!

Please try to re add the device. We hav tested and  can not reproduce the same issue as reported.

**Comment by Finn-Cato** [comment]
I can try do that, but i altso got a problem with flicker on the dimmer, i have 9 namron Namron Alfa reflektor Downlight 10W matt sort and if i dim down to 70% it stop, but if on 100% it flicker, not often, but maybe every 4min or so. is there anything i can do to fix that?

**Comment by prj84** [comment]
Please contact our costumer service regarding this issue. They will help you
https://www.elektroimportoren.no/?Service=mypage&View=contactus
