### ISSUE TITLE
Homey Pro lost connection to Namron

### ISSUE THREAD

**Issue by Tmwe** [NamronAS/Namron_Homey#23]
All of our namron devices suddenly stopped working.

Homey Pro diagnostic ID: 70A5B9
App version: 6.11.5.956
Homey version: 8.0.6

We have tried restarting homey pro.

**Comment by Toremoll** [comment]
I have the same issue on Homey bridge. Also not possible to add new device. 
![Screenshot_20220928_214250_app homey](https://user-images.githubusercontent.com/114617660/192875497-61cfb97b-002b-44e7-9420-74021a1babbc.jpg)

**Comment by Toremoll** [comment]
Now it works again!

**Comment by Tmwe** [comment]
No change here, still not working.

@Toremoll did you do anything to get it up and running?

**Comment by Toremoll** [comment]
@Tmwe No, I did not do anything.. My problem started one week ago.

**Comment by Tmwe** [comment]
Still in need of help!

namron app within homey diagnostic id: 5468cceb-5c5a-4f6b-b64b-fea4c6a692a1

**Comment by Tmwe** [comment]
@prj84
