### ISSUE TITLE
4512752 missing duty cycle card 

### ISSUE THREAD

**Issue by OlavGundersen** [NamronAS/Namron_Homey#232]
When the floor heater termostat is configured as a regulator, the only conntrol cards available are on, off and toggle. The duty cycle / power card is missing. Please add power adjustment option! 

![Screenshot_20240920_234154_Homey](https://github.com/user-attachments/assets/339aa1f9-3e51-46b1-b2f9-e50ddf56cf0e)

**Comment by prj84** [comment]
We will look into it :-)
Thanks for your feedback!

**Comment by OlavGundersen** [comment]
Hi, I am quite new to Github and might be wrong. Sorry if so!
But to me it seems that this case was not assigned to anyone, but just closed. Is this correct if you are supposed to look into it? 🤔

**Comment by philipostli** [comment]
Created a pull request for a solution here: https://github.com/NamronAS/Namron_Homey/pull/235

**Comment by prj84** [comment]
Thanks Philip! We will look into your code!
Olav - Our developer for this device is not on GitHub, so the case was transfered to seperate system.
