### ISSUE TITLE
Long press OFF button fault zigbee 4 chanel swich 4512772

### ISSUE THREAD

**Issue by dalobalo** [NamronAS/Namron_Homey#234]
Using the zigbee 4 chanel swich 4512772.
"When **on** button is **held down**" is working well for all 4 groups. 
"When **off** button is **held down**" is not working for none of the groups. This is true for all flows using the **off** button **held down** function. 

If i try swapping the dim down flow with **on** button there is no issue anymore.
"**Pressed**" and "**Released**" seems to be working.

<img width="590" alt="image" src="https://github.com/user-attachments/assets/1b666415-ba07-464d-8577-5e7a39b173d8">

Led indicator responds on all commands(pressed,held down and released).
Have not tried to replace the unit at Elektroimportøren yet a.

**Comment by prj84** [comment]
Hi! We have tesed the issue and can't really reproduce the problem. Flows with Group 1-4 and with held down triggers all our test flows

**Comment by dalobalo** [comment]
Hi, did you manage to run the flow with a physical button? Im using a 4512700 dimmer btw. When I test  the flow from the pc it works.  Only with the physical button it fails during the off button held down command. 

This simple flow also fails, so maybe its the switch then. I will try to replace it.
![image](https://github.com/user-attachments/assets/689c2d87-a589-47d0-98be-eb34e847f418)

**Comment by dalobalo** [comment]
It automatically downloaded the 2.2.99 version. Was not aware of other versions in Homey.
Installed the experimental test version 2.2.102 and it works..
