### ISSUE TITLE
Namron Zigbee thermostat 16A

### ISSUE THREAD

**Issue by stian303** [NamronAS/Namron_Homey#236]
I have a issue that resently all my thermostats show that they are set at 26 degrees in homey. At the display om the thermostat is shows the correct set temp. If I reset namron app it shows correct and then lt show wrong again at a different day. I have 4 thermostats with this error. It was not like this earlier. Also more people on Facebook have the same issue.

![IMG_3092](https://github.com/user-attachments/assets/a6cace7e-857c-4b3a-959b-fee0c26c4290)
![IMG_3093](https://github.com/user-attachments/assets/a2897300-df8d-40ed-9cc6-0c4cb4959f39)

**Comment by prj84** [comment]
Reported to developer

**Comment by Alpacay** [comment]
@stian303 Hello, Can you post the thermostat image when the app shows the wrong deg？ The app does not update degrees unless the device reports new degrees

**Comment by stian303** [comment]
> @stian303 Hello, Can you post the thermostat image when the app shows the wrong deg？ The app does not update degrees unless the device reports new degrees

Hi, 
I it seems like this is fixed for now. My thermostats shows correctly.
![IMG_3122](https://github.com/user-attachments/assets/2103c538-9b9f-4efd-a40b-4fd44c17d12a)

**Comment by stian303** [comment]
Still issue, checked today.
![IMG_3128](https://github.com/user-attachments/assets/75e54319-c295-4f30-9634-88e43d40dd98)

**Comment by prj84** [comment]
Should be fixed with lates app update - Pushed for approval as we speak.
