### ISSUE TITLE
Namron Z-Wave Relé 16A (4512746) - Status after power failure

### ISSUE THREAD

**Issue by matswhansen** [NamronAS/Namron_Homey#24]
Hi.
Any possibility to add the option to define if the relay should be on or off after a power failure, as Aeotech Heavy Duty switch?
Will mount two of these on my heatpumps, just to measure current, and I want them to always be on.
![image](https://user-images.githubusercontent.com/115462542/194839357-c2fad786-4d08-45d7-a628-9dc83ea3aefc.png)

**Comment by prj84** [comment]
Please try  to readd devices after new v2.2.57 app is certified and published. We have clasified the devices as socket to give a bit more options than just lighting. It should then be possible to set that device should allways be on in advanced settings in Homey
