### ISSUE TITLE
Namron Smart thermostat 4512744; Set "dry mode" from flow 

### ISSUE THREAD

**Issue by UserAvailableNames** [NamronAS/Namron_Homey#34]
An "Then" card for setting mode of thermostat should be made available.
Setting "dry mode" is already available in Homey app and working fine, but not from a flow.

As an example it would be an advantage to be able to set the thermostat to "Dry mode" when high humidity have been detected.

Only option pr. now is to increase the setpoint, and revert it later instead of the defined time in the thermostats schedule.
This is not optimal as one would need make sure it is reverted to original value.

**Comment by UserAvailableNames** [comment]
As an workaround one can send z-wave command directly, but requesting that setting mode will officially be supported by namron APP

<img width="1479" alt="Capture" src="https://user-images.githubusercontent.com/121623754/209972083-8dcd09ca-683c-481b-ba35-b56371556ae4.PNG">

**Comment by henninglensberg** [comment]
Hi What app do you use to send z-wave command directly?

**Comment by henninglensberg** [comment]
> 

Hi
Do you have  a list over all possible commands to send?
