### ISSUE TITLE
Stove guard

### ISSUE THREAD

**Issue by Krisch2** [NamronAS/Namron_Homey#35]
I've got an issue with the stove guard stop reporting power consumption. Only way get it report is a full restart og the stove guard, a restart of the Namron app do not help.
Any suggestion to overcome this problem?
I'm using the power meter reporting for several flows in Homey that doesn't work as intended due to this issue. Are there any firmware updates available?

**Comment by b1ue3AGLE** [comment]
I've have the same issue, no kWh reporting on Namron Stove Guard.

**Comment by jmeland1** [comment]
I have the same issue on my stove guard
