### ISSUE TITLE
Namron device not working from Homey Pro

### ISSUE THREAD

**Issue by Tor-Aksel** [NamronAS/Namron_Homey#38]
After installing Homey Pro software version 8.1.2, the Namron device doesn't communicate with Homey. The device itselves work as normal, but not from Homey. Within Homey Pro the device seems as shut down and not possible to switch on again.

**Comment by knut-stut** [comment]
Hi

I experience the same problem. Other devices connected to Homey is working, but everything from Namron is not connectable. Any solutions?
