### ISSUE TITLE
Thermostats does not report energy or watt

### ISSUE THREAD

**Issue by henninglensberg** [NamronAS/Namron_Homey#39]
Hi
I have 5 thermostats, 3 zigbee and 2 z-wave.
There are only one of the thermostats that reports "Energy" and "Effekt/Watt"
All says last uptate "one month"

Temperature for both Room- and flor sensors is updated often - and seems to work fine.

**Comment by erbrauti** [comment]
I have more or less the same problem, mine uses several hour to change “Effekt”. Yesterday it reported 946w constant in 7 hours. But for energy it seems to update continuously.

**Comment by frode1814** [comment]
I have 2 Zigbee thermostats and also have problem with update on Energy and Effekt.

**Comment by henninglensberg** [comment]
It sounds crazy, but after uninstalling "Sparegris" on my Homey, all thermostats report fine.
