### ISSUE TITLE
Set time and date with flow

### ISSUE THREAD

**Issue by henninglensberg** [NamronAS/Namron_Homey#40]
Hi

I hope that you for termostats (and other devices having time/date) can create flows that can set/update time and date in the device.
When going to/from summer/wintertime it is needed.
It also seems like clock on termostat are going to slow, about 10 min for a month

/henning

**Comment by prj84** [comment]
Thanks for feedback, we will look into this!

**Comment by henninglensberg** [comment]
Hi
I can see it is closed as completed. When will it be implemented in Homey app for users?

**Comment by henninglensberg** [comment]
Hi @prj84 
Has this been deployed?
Still having wrong date/time on 4512744/45 and 4512737/38 

It says its closed as competed, but cant see any changes
