### ISSUE TITLE
App crashes several times a day

### ISSUE THREAD

**Issue by erbrauti** [NamronAS/Namron_Homey#42]
My Namron app is crashing all the time, have tried to reinstall it several times. After reinstall it works good for a while typically 1-5 hours.
![49CF4BB0-8F33-4052-83DF-AA04EB1624F3](https://user-images.githubusercontent.com/70229546/216728345-3c56a2d6-7765-42fe-a631-4c61ec5d287f.jpeg)
![C0DBCD0B-7CFE-4367-BDE5-12535196F328](https://user-images.githubusercontent.com/70229546/216728349-06715590-6017-41b3-8388-812170dd0062.jpeg)

**Comment by erbrauti** [comment]
Problems seems to be solved after installing v2.2.60.

**Comment by murela** [comment]
I have the same issue. It started about a week ago and it has become totally unpredictable. Crashes multiple times each day. See report id 901137a7-e81a-4e52-8398-191cc9322a86

**Comment by prj84** [comment]
App update out now! :-)
