### ISSUE TITLE
Luna

### ISSUE THREAD

**Issue by Roaldoien** [NamronAS/Namron_Homey#44]
With 2.2.58 - cant change led temperatur colour. Only blue white light.

**Comment by Roaldoien** [comment]
Update on this? Possible to get this working on the Luna lamp?

**Comment by prj84** [comment]
Hi! I have forwarded the issue

**Comment by Roaldoien** [comment]
Saw this hot closed. Is there a solution? Still only cold white when adding luna.

**Comment by Roaldoien** [comment]
> Hi! I have forwarded the issue

@prj84 noe nytt med fargen på lyset?
