### ISSUE TITLE
"Namron is temporarily unavailable"

### ISSUE THREAD

**Issue by RobinHavre** [NamronAS/Namron_Homey#45]
> "Namron is temporarily unavailable, it will be back shortly."

We installed Namron Z-Wave Dimmer 400W (Namron Aktuator 4512710) several places in our apartment, and hooked it all up to the Homey Bridge.

In the beginning this worked perfectly, but for the past two weeks we keep getting the error ``"Namron is temporarily unavailable, it will be back shortly."``.

This happens several times per day, and more often than not we cannot control our lights. 

Has anyone else experienced this? 

<img width="422" alt="Screenshot 2023-02-05 at 17 17 29" src="https://user-images.githubusercontent.com/3342645/216919632-4b8b03dd-8410-4e14-a387-e4cae31403e4.png">

<img width="432" alt="Screenshot 2023-02-06 at 09 17 28" src="https://user-images.githubusercontent.com/3342645/216920285-2ab91dd9-dff4-4461-87da-229c83a01877.png">

**Comment by jarleraa** [comment]
Same for zigbee dimmer and thermostat.

**Comment by murela** [comment]
I have the exact same issue. Only way to solve is to re-install app via Homey store. Needs to be done several times pr day.

**Comment by jarleraa** [comment]
Get the new version currently in test. 2.2.61. Solved my issues.

**Comment by murela** [comment]
Seems to solve the issue for me too.

**Comment by GeirLiknes** [comment]
> Get the new version currently in test. 2.2.61. Solved my issues.

I'm new to this, where to find the new version?

**Comment by murela** [comment]
Click on “version history” on the app page and install the test-version.

**Comment by murela** [comment]
I've been running the testversion (2.2.61) for a few weeks and that version works perfectly. Updated to version 2.2.64 yesterday, and the issue with the app crashing is back :(

**Comment by GeirLiknes** [comment]
Same here, testversion 2.2.61 worked fine but after update to 2.2.64 we are back to dark rooms :(
Would be fine if this units can start working again, they cost some money and I would like to have them do the job ;)
