### ISSUE TITLE
Namron zwave devices not available

### ISSUE THREAD

**Issue by markusv** [NamronAS/Namron_Homey#48]
Hi,

i have a problem with my Namron zwacke light switches. The show error message device not availabe. Cannot read properties of undefined. See attached screenshots. The devices I have problem with are of type 1402756 z-wave rotary dimmer. I have version 2.2.61 of the namron app. 
 
 i have created a crash report: 96071e2e-0e97-4402-a06b-bb7b70657aa4

please help. Let me know if I can help debugging. 

![0CEBD460-5CCD-4889-8110-887E8199212A](https://user-images.githubusercontent.com/475663/218563062-6a4b8fcc-7e10-4b0b-b9b7-c84f5a4889f6.png)
![788DE84C-583A-4EA9-BC1A-E70E9681947C](https://user-images.githubusercontent.com/475663/218563075-c6dad32c-b8d7-4ab1-ba20-162d83acfee5.png)

regards 
Markus

**Comment by prj84** [comment]
A fix should be pushed out today
