### ISSUE TITLE
Dim Duration

### ISSUE THREAD

**Issue by thomasdt94** [NamronAS/Namron_Homey#49]
Somehow dim duration does not work on this dimmer? It just skips the time entered in the duration field and goes straight to the entered level.

**Comment by prj84** [comment]
On what device? :-)

**Comment by thomasdt94** [comment]
Namron Z-Wave LED Dimmer

**Comment by prj84** [comment]
Turnable or puck?

**Comment by thomasdt94** [comment]
Turnable
