### ISSUE TITLE
Komfyrvakt 1402793 Not turning back on

### ISSUE THREAD

**Issue by KataKidden** [NamronAS/Namron_Homey#51]
After turning off the komfyrvakt, it will not turn back on from Homey. 
Pressing the button on the device turns it back on and reports it to Homey. 
Error reads: En ukjent feil har oppstått [null]

**Comment by prj84** [comment]
It is not allowed to turn on the device from the app. This so you can not turn on the stove from remote location.

**Comment by zub** [comment]
@prj84 Does the device really need to disconnect from the zigbee network in order to prevent that?
