### ISSUE TITLE
Namron app krashes constantly. Homey bridge installation

### ISSUE THREAD

**Issue by risaasen** [NamronAS/Namron_Homey#52]
Hi.
Haveing several Namron Zigbee dimmers in house this is extreemely frustrating. 
Any news about when this issues can be fixed ?¨
Restart, and works 1-2 times. Then crash againg.

**Comment by GeirLiknes** [comment]
Same with me! I have five Namrom 1402755 Zigbee dimmer mainly not responding when connected to Homey Bridge. Homey says app crash. All five was fully operated with Samsung Smartthings, but with Homey Bridge they are only responding a few times a day. Frustrating!

**Comment by ibiubu** [comment]
I have the same problem with  4512725-z and 4512700/33 and homey bridge.

**Comment by GeirLiknes** [comment]
After installing beta-app 2.2.61 it is all sunshine :)

**Comment by GeirLiknes** [comment]
![Screenshot_20230226_194635_Chrome](https://user-images.githubusercontent.com/126382466/221430464-96ffe42d-1190-4df0-9130-4c58ac728ccc.jpg)

**Comment by ibiubu** [comment]
When will this .61 version be pushed to Homey Bridge? Is it Homey’s responsibility or the app developer?

**Comment by ibiubu** [comment]
> When will this .61 version be pushed to Homey Bridge? Is it Homey’s responsibility or the app developer?

Oh, I got it. It was just to push the right buttons as shown in above screenshot. It turns out also the bridge supports experimental app versions. Thanks guys.

**Comment by prj84** [comment]
A temp fix should be pushed out today that should resolve the issue
