### ISSUE TITLE
Zigbee toutch 16ah thermostat

### ISSUE THREAD

**Issue by vitor029282** [NamronAS/Namron_Homey#57]
Wont work before and after update. Works 15min after connecting to hub and wont work in the app. Susdenly after update it worked for about 4-5 hours before namron app crash again

**Comment by prj84** [comment]
Hi! Lates update that is in test should fix the problem.
Please install - https://homey.app/no-no/app/net.filllip-namron/Namron/test/
Or wait for Homey to Athom to approve the update
