### ISSUE TITLE
Issue with Namron app crashes on Homey.

### ISSUE THREAD

**Issue by Garden08** [NamronAS/Namron_Homey#58]
Hi, 

I have installed the Namron app (v2.2.64) on Homey and have added two Namrom Zigbee heaters (510139)
The first one worked for about 10 minutes, but after adding the second heater, the app crashes. 

I have tried to remove and reinstall the app, but the same problem occures.

Any Ideas?

**Comment by Tryham** [comment]
Same. App crashes all the time. If I want to change temperature, I need to install the app again, and then change.
Also, termostat does not work.

**Comment by prj84** [comment]
Manufactorer is working on a fix, we will publish as soon as it is ready!

**Comment by prj84** [comment]
update in test as we speak! Please test!

**Comment by prj84** [comment]
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by Garden08** [comment]
Thanks for the quick update :-)

I have installed it now and will give it a test. So far, it seems good though :-)

**Comment by Tryham** [comment]
Tested about two hours, and it's working like a charm right now. App has not crashed, and I can change temperature through tibber and homey

**Comment by Garden08** [comment]
Same here! 
Seems to be working very good.
