### ISSUE TITLE
Missing cluster

### ISSUE THREAD

**Issue by elengineer** [NamronAS/Namron_Homey#63]
A few of my devices now reports «missing cluster» after the new official version. Tried to update to the test version, but same issue. 

This issue is impacting the Zigbee dimmers
![1FB21A91-27C9-4093-AD54-E74A3CD0DC80](https://user-images.githubusercontent.com/75915697/224147678-6b47e3d0-a7b9-4ea6-8b59-f59545db1f7e.png)

**Comment by prj84** [comment]
Article number?

**Comment by joakimroer** [comment]
I have this broblem with article number 1402755 Namron zigbee 200w dimmer.

**Comment by joakimroer** [comment]
> I have this broblem with article number 1402755 Namron zigbee 200w dimmer.

I have this broblem with article number 1402755 Namron zigbee 200w dimmer.

**Comment by prj84** [comment]
Thanks for feedback
