### ISSUE TITLE
Namron Zigbee Thermostat Touch

### ISSUE THREAD

**Issue by christerjt** [NamronAS/Namron_Homey#66]
The device page for this thermostat shows "Nåværende temperatur/Current temperature" on the first page. This temperature is not correct. Se attached pictures, pic. 1 and 2 are the same device at the same time. I have 3 of this device and the same problem on all of them. ProductId: 4512737

![Namron1](https://user-images.githubusercontent.com/124155096/224672902-ef3ac118-7f3f-4557-98f8-1383e2786b29.png)
![Namron2](https://user-images.githubusercontent.com/124155096/224672914-e36a43c8-0b99-475a-9769-48b761001688.png)

**Comment by christerjt** [comment]
The last 3 days this has been working. 
No update to the Namron App in the periode, so I assume this has been fixed in the Homey Cloud.

**Comment by prj84** [comment]
Thanks for feedback - Please come back if the problem comes back :-)
