### ISSUE TITLE
Everything Crashes when I push a button

### ISSUE THREAD

**Issue by Muffia** [NamronAS/Namron_Homey#67]
Hello,

I installed several switches and dimming pills in my apartment. When I try to do anything (pushing a button or turning on lights in the homey app) it suddenly crashes. 

Yesterday I was unable to turn my bedroom lights off!!

Please help!

**Comment by ibiubu** [comment]
I can confirm that Namron app still crashes on Homey bridge with .67 version. These Namron devices just becomes not usable. They don’t work. And we as users don’t get any value out if it.

**Comment by prj84** [comment]
Same as https://github.com/NamronAS/Namron_Homey/issues/65
