### ISSUE TITLE
With update 2.2.67, no Zigbeee rotary dimmers responds

### ISSUE THREAD

**Issue by rubenhansen** [NamronAS/Namron_Homey#68]
![IMG_CDC2C8ADCBA7-1](https://user-images.githubusercontent.com/26575696/228011751-be2f5c52-7fd0-468f-bf68-75a247e30925.jpeg)

**Comment by sbryne** [comment]
Same here, with Z-Wave dimmers.
![Uploading 4A8D510E-7488-482D-AFCA-A726F7804EA1.png…]()

**Comment by RoGoin** [comment]
Same here with all my Z-Wave switches and a wall plug. 
![B9634128-39EF-4DAF-96BE-9C7124D907B6](https://user-images.githubusercontent.com/129151734/228153349-09d052e4-d403-4ef4-9672-d33b43080257.png)

**Comment by RoGoin** [comment]
Seams like the developer has an answer in a facebook group. Doesn’t help me anything because 
I’m not on facebook.

https://www.facebook.com/groups/1749985315078059/posts/6039335099476371/?__cft__%5B0%5D=AZW1EtP33R4Ws75vqBEWcD4XDnt7zFh1q0SYbFV2XLYZ0jL9rj4LAw2dYhLL8P-LTO90VhkE7i2grfPGJ_M40H2sh2VnpLpAerSFAvUpzC46C7N6BvHV

**Comment by prj84** [comment]
Namron app oppdatering - 2.2.67
Jeg legger ut denne informasjonen her siden en del brukere er påvirket
Athom har gitt oss beskjed om å fjerne utgåtte drivere i arbeidet med å finne mulige feilrettinger for app problemer i deres skytjeneste.  Som mange har opplevd så krasjer appen i tide og utide i skytjenesten til Athom. Eneste løsningen Athom har for hånden er å redusere devicer og flows. Vi så oss derfor nødt til å fjerne disse for å få en stabil tjeneste/app igjen. Dette i påvente av at Athom får laget en fiks på sine servere. ETA på dette er usikkert da HP23 er prioritet 1. App oppdateringen skulle ikke gått igjennom før vi fikk kommunisert ut dette, men ble publisert en dag for tidlig av Athom crewet igår.
Vi beklager at dette krever reinkludering av enheter for å få disse igang igjen for en del brukere, men vi så ingen annen mulighet. Bonusen er at dere får de nyeste driverne for deres enhet, som inkluderer en del feilrettinger.
Vi beklager så mye igjen. Dessverre eneste muligheten pr nå for å få gitt alle brukere stabile tjenester på Homey plattformen.

**Comment by sbryne** [comment]
Also, it seems like the answer is in a closed group (I cannot access it).

I’ve circumvented the whole Namron app by re-adding my devices through the UnZ-Cure app - now the devices actually work better than before.

**Comment by prj84** [comment]
Hei!

Denne posten i Homey community gir en god forklaring på hvorfor dette ikke fungerer lenger. Dette basert på at Z-Wave inkluderingen nå benytter den høyeste mulige sikkerhetsnivået enheten kan håndtere. Kun enheter med DSK kode kan man tvinge igjennom en inkludering unsecure ved å benytte kode 00000.

Utover dette må man benytte UnZ-Cure appen for å få en unsecure kobling.

Post til utvikler av UnZ-Cure hvor han forklarer hvordan appen fungerer:
https://community.homey.app/t/app-pro-unz-cure-add-z-wave-devices-unsecure/55597

Vi har vært på Athom for å gi en lignende inkluderingsprosess som f.eks Futurehome benytter hvor man selv kan velge sikkerthetsnivå. Foreløpig uten å komme igjennom.

**Comment by RoGoin** [comment]
A workaround for the z-push button is to add them via the Heat-it app. That worked for me. For the wall plug and switch I have no workaround.
![913EEFED-4784-4073-A19A-922E89D7C6DA](https://user-images.githubusercontent.com/129151734/228221328-6e338638-631e-41c7-b274-afde4b98ffad.png)

**Comment by prj84** [comment]
Try to add the with the Heatit push button driver. The security level is set in the initial pairing prosess. It will select correct driver automatically.
