### ISSUE TITLE
Fail to have touchlink and flow at the same device, Homey Pro 2023

### ISSUE THREAD

**Issue by joakimroer** [NamronAS/Namron_Homey#74]
Hi
On my Homey Pro 2019 I had many Namron panel K4 and K8 that for example group 1 was touchlinked to a bulb and group 2 had a flow to steer volume on my radio.
I did and backup and restore to my new Homey Pro 2023 and now I can only choose to have touchlink or flow.
I have tried to remove the devices and connect again but same problem.

I can connect both bulb and panel to Homey and make an flow for group 2. Then it work.
If i then touchlink group 1, flow on group 2 won't start.

**Comment by prj84** [comment]
Do the flow get a error when you try to start? Is it possible to use the device manually in the app when using TouchLink? If one og the channels on the remote is TouchLinked, is it then not possible to use flow on any other channels?

**Comment by joakimroer** [comment]
> Do the flow get a error when you try to start? Is it possible to use the device manually in the app when using TouchLink? If one og the channels on the remote is TouchLinked, is it then not possible to use flow on any other channels?

Nei, kommer ikke noe error. Kan evt. prøve å lage et error-kort i AF.
På badet f.eks, så har jeg følgende:
1 stk Namron Zigbee LED dimmer - 1402755
1 stk Namron Zigbee 2 Kanal K4 - 4512719

Begge 2 ligger i Homey og de er touchlinket på kanal 2, slik at jeg kan slå av/på lyset samt holde inne for dimming.
På kanal 1 så har jeg aktivering av flow som øker eller senker volum på radio.
På kanal 2 så har jeg flow som kjører vvb 1 time og jeg trykker på PÅ på kanal 2 og lys er slått på.

Dette har fungert i 2 år med Homey Pro 2019.

Dersom jeg sletter enhetene i Homey og legger inn på nytt, så fungerer flowene slik de skal. Om jeg så aktiverer touchlink mellom enhetene, så virker touchlink, men flowene slutter å fungere. Skjer ingen ting når jeg trykker på knappene for aktivering av flow.

**Comment by prj84** [comment]
@joakimroer - Hva er status her etter at Homey har oppdatert og gjort en del endringer på zigbee core for 2023?

**Comment by joakimroer** [comment]
Ingen endring.

Testet følgende nå:
Fjernet Namron dimmer og Namron bryter fra Homey.
Resatte bryter og dimmer.
La inn på vanlig måte.
Lagde en flow på gruppe 2 på bryter. Da fungerer flow.
Så touchlinket jeg dimmer og Gruppe 1 på bryter, da fungerer ikke flow på gruppe 2.



Mvh
Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Pål Hefre ***@***.***>
Dato: 31.07.2023 11:56 (GMT+01:00)
Til: NamronAS/Namron_Homey ***@***.***>
Ko: joakimroer ***@***.***>, Mention ***@***.***>
Emne: Re: [NamronAS/Namron_Homey] Fail to have touchlink and flow at the same device, Homey Pro 2023 (Issue #74)


@joakimroer<https://github.com/joakimroer> - Hva er status her etter at Homey har oppdatert og gjort en del endringer på zigbee core for 2023?

**Comment by prj84** [comment]
Issue resolved - New firmware and recall
