### ISSUE TITLE
No feedback from 1402755

### ISSUE THREAD

**Issue by elengineer** [NamronAS/Namron_Homey#77]
I have lost feedback from the Rotarty Zigbee dimmers (1402755) when operating them localy. 

Have tried to remove and re-add the devices, but no luck.

**Comment by prj84** [comment]
Hi! What Homey gateway version are you using? Firmware?

**Comment by elengineer** [comment]
HP19, 8.1.3.

**Comment by maginawin** [comment]
Hi @elengineer ,
Has it worked before?

**Comment by elengineer** [comment]
Yes, I have not updated the Namron app for a while, but when I updated I lost feedback from all the 1402755 devices.

**Comment by elengineer** [comment]
Tried again yesterday with re-adding devices, and somehow its seems like the problem is solved. 

Maybe it could be a Homey issue?
