### ISSUE TITLE
Why does my Namron products stop working?????

### ISSUE THREAD

**Issue by NetromNeslo** [NamronAS/Namron_Homey#78]
I am so tired of resetting and adding all my products to homey. They stop working every other week. I have to reset and add all name on products and redo all my flows.

I will soon send back all my products ( 9 thermostats and 3 led dimmers, some sockets and switches) if it is not possible to fix this issue soon.

**Comment by prj84** [comment]
We need some more information on the problem you are facing. What kind of products is falling out? Distance? Any other products you are using in same zigbee network?
