### ISSUE TITLE
4512725 - Z wave thermostat (Homey Bridge)

### ISSUE THREAD

**Issue by torpedoz** [NamronAS/Namron_Homey#80]
After re-adding the 4512725  (because the app/device stopped responding) - the status indicator which enables you to choose displaying temperature, energy, effect or none is not available, it only shows default temperature.

Before re-adding the device was set to show effect (W) - my other 4512725 still shows this property.

Have tried re-adding the plug in Homey several times, but status indicator is still unavailable. Anyone who knows how to fix this ?

**Comment by prj84** [comment]
We will have a look

**Comment by torpedoz** [comment]
Hi @maginawin 
> Actually worked like a charm on the one device I tested on! - Thanks!  - Will try on the other one with same issue as well, trust it goes equally smooth.

I also learned the same time how fast the 3 clicks should be, to re-add the device to Homey. 



> Hi @torpedoz , Reset the device by press and hold down the action button on the device for over 10 seconds, and then re-add it again, will it works?

**Comment by prj84** [comment]
Thanks for feedback!
