### ISSUE TITLE
Extreme high battery usage on Namron Z-Wave Multisensor - 4512734

### ISSUE THREAD

**Issue by joakimroer** [NamronAS/Namron_Homey#81]
Hi
I bought an Namron Z-wave Multisensor in february and I have already change the batteries 3 times. Is this normally or is there something wrong with my Multisensor?
In my garage I have 10 celsius

![zcvzc](https://user-images.githubusercontent.com/84479112/232714223-4e30d993-bc2d-405b-bd34-6ea631d8a375.JPG)
![cfv](https://user-images.githubusercontent.com/84479112/232714246-c3ae7f9c-d356-49ba-a434-88192c4c029a.JPG)

**Comment by prj84** [comment]
Hi!
We have not got any feedback on this issue. Can you please try to reset and re-add the device to see it the problem is still there?
