### ISSUE TITLE
Namron z-wave Rotary dimmer 

### ISSUE THREAD

**Issue by nilsenen93** [NamronAS/Namron_Homey#86]
Hi, I have connected four of these dimmer, going from SmartThings hub to New Homey Pro 23. But none of the dimmer seem to show any power data, like current Watt or used kWh. They showed this in Samsung SmartThings before.

Is this possible to fix in an update?

**Comment by prj84** [comment]
Hi!

There is a part missing in the Z-Wave implementation on Homey that this dimmer use. So as you say it works with ST and other hub manufactorers. Out supplier is working on a fix, but we are not 100% shure it will work and when it it ready.
