### ISSUE TITLE
Battery indicator not working on z-wave 1-ch and 2-ch controller

### ISSUE THREAD

**Issue by thomahawk72** [NamronAS/Namron_Homey#87]
Homey Pro early 2023, 10.0.0-rc.105
Namron app 2.2.67.

Added two controllers: 1-channel and 2-channel z-wave.
No battery information is displayed for either of the two.
Beside this, both controllers works properly.

**Comment by prj84** [comment]
Hi! Thanks for feedback!
We will look into this!

There seems to be a change in Z-Wave implementation resulting in this error.

/Pål
