### ISSUE TITLE
Missing flowcards for Zigbee Thermostat 4512737

### ISSUE THREAD

**Issue by areluke** [NamronAS/Namron_Homey#91]
App works great but flowcards to set heating mode on Zigbee Thermostat Touch is sorely missed. The setting is available in device manager. Turning the thermostat on and off in flows can cause it to inadvertently change its mode with no way to automate it back to manual or auto (schedule) mode, also making its internal schedule system unusable.

**Comment by prj84** [comment]
Hi!
We will discuss this with supplier! 
Thanks for feedback!
