### ISSUE TITLE
3802967 - bulbs constantly losibg connection and trouble to recon

### ISSUE THREAD

**Issue by NorNicosu** [NamronAS/Namron_Homey#92]
I have four of these (sorry, not sorry) rubbish light bulbs on one light connected to homey pro (not the newest) .

During my ownership of these, i have almost never been able to use their functionalities (dim and colours) because these *** almost never stay connected / connect to Homey.

I have restarted Homey, reset Homey, reset zigbee network, reset bulbs and more, it seems.. sometimes it helps; usually it doesnt.

**Comment by prj84** [comment]
Hi!
We have 20000+++ in the market of these bulbs and a issues are really low. Can you please tell us about distance fro Homey, any other powered zigbee devices near/between?

**Comment by prj84** [comment]
no feedback - please reopen if issue persist
