### ISSUE TITLE
Namron not working with Homey after update

### ISSUE THREAD

**Issue by Nickeponken** [NamronAS/Namron_Homey#94]
Hi. My Namron units are not working after the latest update. According to the Norwegian Homey page on Facebook, several are struggling with the same problem. Please look into this asap, really urgent.

**Comment by jon-boop** [comment]
I have the exact same problem. The Homey unit, and other devices are working fine, but not namron zwave units. I have restarted the unit several times. So now I have no lights in my home

**Comment by Nickeponken** [comment]
Ok.

I have sent an email to Namron, so we will see what they reply..

lör 15 juli 2023 kl. 21:02 skrev jon-boop ***@***.***>:

**Comment by prj84** [comment]
Hi!

There has been no changes on the app since 2. May 2023. when there was added new devices. 

We have put a update in the test inviroment today for you to test where we have reintroduced some old drivers we needed to remove when Athom had issues with their Homey Cloud:
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by Nickeponken** [comment]
Not sure what you want med to do. I actually restarted the app and Homey 5
mins ago, and the result was the same..

mån 31 juli 2023 kl. 11:34 skrev Pål Hefre ***@***.***>:

**Comment by prj84** [comment]
Please try to install the test app. Link in the last post.31. jul. 2023 kl. 11:39 skrev Nickeponken ***@***.***>:﻿
Not sure what you want med to do. I actually restarted the app and Homey 5

mins ago, and the result was the same..



mån 31 juli 2023 kl. 11:34 skrev Pål Hefre ***@***.***>:

**Comment by Nickeponken** [comment]
Ok. The lights are working now. So I should only use this app in homey now?

mån 31 juli 2023 kl. 13:19 skrev Pål Hefre ***@***.***>:

**Comment by prj84** [comment]
Good news :-) You can install the stabile (non test version) as soon as the .70 is approved by Athom. I will close this now. Please reopen if you get any problems related to this :-)

**Comment by Nickeponken** [comment]
Ok.
Only a comment. I can’t turn the light on and off, I have to go in on the
specific light and dim up or down.

mån 31 juli 2023 kl. 22:31 skrev Pål Hefre ***@***.***>:
