### ISSUE TITLE
Namron 4512737/4512738 not connecting 

### ISSUE THREAD

**Issue by Bekkenes** [NamronAS/Namron_Homey#97]
Moving back to homey after a year with home assistant but these won't connect or be found.  Pairing mode as per usual , but doesn't get found in homey.   Other zigbee gets found.  Starting z2mqtt and enable pair mode and it goes in right away.  

Please fix, this is a namron problem.

**Comment by Bekkenes** [comment]
I'm unsure if it's just the manual who is wrong or something else but after lots of trial and error I found out what to do to get it connected to homey :
You start the pairing on the homey app, then you go to the network and set it to connect.  

This will fail if left to its own devices,  but if you reset the thermostat while already in pairing / connect mode, the screen will turn off and the pairing process in homey will work and it gets in .

Can be nice to know for others.  
I removed it 4 times and tried without doing this , same issue.  But if I do as above it works.

**Comment by prj84** [comment]
We will have a look! Thanks for feedback!
